# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build

on:
  workflow_dispatch:
  push:
    branches: [ "develop" ]

env:
  DOTNET_VERSION: '8.0.x'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Restore dependencies
      run: dotnet restore ./CleanArch.sln
      
    - name: Build
      run: dotnet build ./CleanArch.sln --no-restore
      
    - name: Test
      run: dotnet test --filter FullyQualifiedName!~CleanArch.Benchmarking ./CleanArch.sln --no-build --no-restore --verbosity normal
